name: REL

on:
  push:
    branches: [master]
  pull_request:

jobs:
  bundle:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - run: pnpm install
      - run: cd workspace/extension && pnpm build
      - run: cd workspace/extension/build && zip -r svelte-devtools *

      - uses: actions/upload-artifact@v3
        with:
          name: extension-${{ github.sha }}
          path: workspace/extension/build/svelte-devtools.zip

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: bundle

  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: extension-${{ github.sha }}
