name: REL

on:
  push:
    branches: [master]
  pull_request:

jobs:
  manifest:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - id: extract
        working-directory: ./workspace/extension/static
        run: echo version=$(jq -r '.version' manifest.json) >> $GITHUB_OUTPUT

  bundle:
    runs-on: ubuntu-latest
    needs: manifest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install
      - working-directory: ./workspace/extension
        run: pnpm build && cd build && zip -r svelte-devtools *

      - uses: actions/upload-artifact@v4
        with:
          name: extension-${{ github.sha }}
          path: workspace/extension/build/svelte-devtools.zip

      # debug
      - run: echo ${{ github.event.head_commit.message }}
      - if: github.event.head_commit.message == '~ v${{ needs.manifest.outputs.version }}'
        env:
          GH_TOKEN: ${{ github.token }}
        run: | # https://cli.github.com/manual/gh_release_create
          gh release create v3.0.0 \
          workspace/extension/build/svelte-devtools.zip \
          --title 3.0.0 \
          --draft --generate-notes

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: bundle

  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: extension-${{ github.sha }}
