name: REL

on:
  push:
    branches: [master]
  pull_request:

jobs:
  manifest:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.extract.outputs.version }}

    steps:
      - uses: actions/checkout@v4
      - id: extract
        working-directory: ./workspace/extension/static
        run: echo version=$(jq -r '.version' manifest.json) >> $GITHUB_OUTPUT

  bundle:
    runs-on: ubuntu-latest
    needs: manifest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - run: pnpm install
      - working-directory: ./workspace/extension
        run: pnpm build && cd build && zip -r svelte-devtools *

      - uses: actions/upload-artifact@v4
        with:
          name: extension-${{ github.sha }}
          path: workspace/extension/build/svelte-devtools.zip

      - if: github.ref == 'refs/heads/master'
        env:
          GH_TOKEN: ${{ github.token }}
        run: | # https://cli.github.com/manual/gh_release_create
          gh release create v${{ needs.manifest.outputs.version }} \
          workspace/extension/build/svelte-devtools.zip \
          --title ${{ needs.manifest.outputs.version }} \
          --draft --generate-notes --notes '
          Built from ${{ github.event.head_commit.id }} at https://github.com/sveltejs/svelte-devtools/actions/runs/${{ github.run_id }}
          - Chrome Web Store: https://chrome.google.com/webstore/detail/svelte-devtools/kfidecgcdjjfpeckbblhmfkhmlgecoff
          - Firefox Signed Add-on: https://github.com/sveltejs/svelte-devtools/releases/download/v${{ needs.manifest.outputs.version }}/svelte-devtools.xpi
          ---'

  # publish:
  #   runs-on: ubuntu-latest
  #   needs: bundle

  #   steps:
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: extension-${{ github.sha }}
